# Copy to terraform.tfvars and edit. terraform.tfvars is gitignored.
#
# No passwords here: they are generated by random_password and live only in state and in the
# cluster Secret. That is why this file is short.

namespace          = "vigil"
kubeconfig_path    = "~/.kube/config"
kubeconfig_context = "kind-vigil"
